apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.129.174.225"],"port":32166,"protocol":"TCP","serviceName":"monitoring:grafana-np","allNodes":true}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"grafana-np","namespace":"monitoring"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"grafana"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: "2021-01-26T17:54:29Z"
  name: grafana-np
  namespace: monitoring
  resourceVersion: "822379121"
  selfLink: /api/v1/namespaces/monitoring/services/grafana-np
  uid: 85daf918-f8cd-4195-883b-8e624325f648
spec:
  clusterIP: 10.99.12.175
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32166
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
